### ISSUE TITLE
rimraf is not present in dev dependencies

### ISSUE THREAD

**Issue by ChmielewskiKamil** [warp-contracts/academy#41]
Rimraf is not getting installed during yarn install. It is not present as a dev dependency in package.json.

I don't have it installed globally.

Steps to reproduce:
1. run yarn build 

I get the following error:
/bin/sh: rimraf: command not found
error Command failed with exit code 127.

How to fix it:
add "rimraf": "^3.0.2" to devDependencies

**Comment by asiaziola** [comment]
fixed.
